### ISSUE TITLE
setSliderValue:函数value值判断错误

### ISSUE THREAD

**Issue by be-water-myFriend** [SimonDeCft/HBLockSliderView#1]
首先给作者👍一个,  但是这里有个小小的错误,   正确的判断应该是:
- (void)setSliderValue:(CGFloat)value animation:(BOOL)animation completion:(void (^)(BOOL))completion{
    if (value >= 1) {
        value = 1;
    }
    if (value <= 0) {
        value = 0;
    }

**Comment by SimonYHB** [comment]
thanks

**Comment by SimonYHB** [comment]
thanks
